version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: iuca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=iuca;Username=postgres;Password=password
    depends_on:
      - postgres

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=iuca;Username=postgres;Password=password
    depends_on:
      - postgres

volumes:
  pgdata:
